### ISSUE TITLE
Drop support for Python 3.8 (April 2025)

### ISSUE THREAD

**Issue by srittau** [python/typeshed#12112]
Python 3.8 has reached its end-of-life phase on 2024-10-07 ([PEP 569](https://peps.python.org/pep-0569/#lifespan)).

### January 2025

* [x] Update the documentation. (#13386)
* [x] Update the `oldest_supported_python` key in `pyproject.toml`. (#13386)
* [x] Remove `requires_python >= 3.9` and `python_version >= 3.9` from `METADATA.toml` (#13386)
* [x] Remove 3.8 from CI and test scripts. (#13387)
* [x] Update stubtest allow lists. Also check whether items can be moved to the common allow lists. (#13389)

### April 2025

* [x] Remove 3.8 exclusive branches from stubs. (#13776)
* [x] Remove obsolete stdlib modules (see `VERSIONS`). (#13771)
    * `_dummy_thread`
    * `_dummy_threading`
    * `dummy_threading`
* [x] Replace `typing_extensions` imports: no op for Python 3.8 -> 3.9
* [x] Remove `backports.zoneinfo` from `EXTERNAL_REQ_ALLOWLIST` in `stub_uploader.metadata` (typeshed-internal/stub_uploader#168)

 (Please amend as necessary.)

**Comment by AlexWaygood** [comment]
I think a lot of the "remove redundant version branches" work would be done automatially with we a Ruff autofix if we bumped this: https://github.com/python/typeshed/blob/ad8ecaf2170c3863923a9ab340708d3cdd921610/pyproject.toml#L21

**Comment by srittau** [comment]
I've nearly finished with removing the branches. It's honestly not that difficult and you catch a few things when doing it manually.

**Comment by AlexWaygood** [comment]
oh, I don't object, just thought it might save a bit of work :-) doing it manually is fine, of course!

**Comment by srittau** [comment]
It's also quite relaxing work. DON'T TAKE IT FROM ME!!!!!

**Comment by brianschubert** [comment]
*slowly closes open PR tab*
