### ISSUE TITLE
Implement 3.7 features

### ISSUE THREAD

**Issue by JelleZijlstra** [python/typeshed#1965]
Let's make sure we have all the new features that will go into 3.7 (going off https://docs.python.org/dev/whatsnew/3.7.html).

- PEP 562 (module `__getattr__`) doesn't affect typeshed, but may need implementation work in typecheckers
- Changes from PEP 538, 539, 565, 540 don't affect typeshed
- [ ] PEP 553 (`breakpoint()`) was implemented in #1846.
- [ ] PEP 563 (`from __future__ import annotations`) was implemented in #1880.
- [ ] PEP 564 (`time_ns` and similar) was implemented in #1846.
- [ ] PEP 557 (dataclasses): active PR #1944, will need more work in type checkers.
- [ ] PEP 567 (contextvars): not yet done.
- [ ] https://bugs.python.org/issue30579: TracebackType is instantiable
- [ ] new module importlib.resources, and importlib.abc.ResourceReader
- [ ] argparse.parse_intermixed_args: #1937 adds this
- [ ] https://bugs.python.org/issue30103: b2a_uu new argument
- [ ] https://bugs.python.org/issue30095: new attributes on HTMLCalendar
- [ ] contextlib.asynccontextmanager: added by #1432 
- [ ] contextlib.AbstractAsyncContextManager
- [ ] contextlib.AsyncExitStack: added by #1876.
- [ ] crypt.mksalt rounds parameter (python/cpython#4110)
- [ ] datetime.fromisoformat (https://bugs.python.org/issue15873)
- [ ] http.client blocksize support (https://bugs.python.org/issue31945)
- [ ] http.server directory parameter (https://bugs.python.org/issue28707)
- [ ] hmac.digest (https://bugs.python.org/issue32433)
- [ ] locale.formatstring `monetary` argument (https://bugs.python.org/issue10379)
- [ ] math.remainder
- [ ] os.fwalk bytes paths (https://bugs.python.org/issue28682)
- [ ] os.scandir fd support (https://bugs.python.org/issue25996)
- [ ] os.register_at_fork (https://bugs.python.org/issue16500)
- [ ] pdb.set_trace header argument (https://bugs.python.org/issue31389)
- [ ] sqlite3.Connection.backup (https://bugs.python.org/issue27645)
- [ ] sys.flags.dev_mode
- [ ] tkinter.ttk.SpinBox
- [ ] time.CLOCK_* (three added)
- [ ] time.thread_time(_ns)? (https://bugs.python.org/issue32025)
- [ ] unittest.mock.seal (https://bugs.python.org/issue30541)
- [ ] uu.encode backtick argument (https://bugs.python.org/issue30103)
- [ ] zipfile.create_archive new arguments (https://bugs.python.org/issue31072, https://bugs.python.org/issue31638)
- [  ] some removals (https://docs.python.org/dev/whatsnew/3.7.html#api-and-feature-removals)
And there's more but I'm out of time.

**Comment by JelleZijlstra** [comment]
All the PRs have been merged, thanks @gvanrossum.

**Comment by gvanrossum** [comment]
You're welcome! Hopefully this will get some testing in next week's release. (Sadly we don't have time yet to write a dataclasses plugin.)
