### ISSUE TITLE
PEP 604 (Unions with pipe character) tracker

### ISSUE THREAD

**Issue by srittau** [python/typeshed#4819]
This issue is supposed to track when we can start to use the pipe character as union ([PEP 604](https://www.python.org/dev/peps/pep-0604/)) in typeshed. Support is needed in released versions of:

* [x] mypy (python/mypy#9610), mostly works, except (full list of related issues [here](https://github.com/python/mypy/labels/topic-pep-604)):
    * [x] Type aliases (python/mypy#10901)
    * [x] https://github.com/python/mypy/issues/12392
    * [x] https://github.com/python/mypy/issues/12393
    * [x] https://github.com/python/mypy/issues/11098
    * [x] https://github.com/python/mypy/issues/14158
* [x] pytype (google/pytype#924)
* [x] pyright (microsoft/pyright#659)
* [x] pyre
* [x] PyCharm ([PY-44974](https://youtrack.jetbrains.com/issue/PY-44974))

**Comment by srittau** [comment]
@rchen152 @mrkmndz Do pytype/pyre support PEP 604? If not, would you mind me creating a ticket in the respective projects that we can reference from here?

**Comment by sproshev** [comment]
Not yet supported by PyCharm https://youtrack.jetbrains.com/issue/PY-44974

**Comment by rchen152** [comment]
This is not yet supported by pytype. Opened https://github.com/google/pytype/issues/785.

**Comment by JelleZijlstra** [comment]
Pyre already supports this. If I'm reading https://youtrack.jetbrains.com/issue/PY-44974 correctly, PyCharm already supports it enough for us to use it. That leaves only pytype.

**Comment by srittau** [comment]
This is the #1 feature I'm waiting for. This means we can basically replace any `Union` and `Optional` in Python 3 typeshed with a more readable alternative.

**Comment by srittau** [comment]
I think this is ready to be tested.

**Comment by srittau** [comment]
Reopening for now due to a fix for python/mypy#10901 not being released, yet. This means, we can't use this in type aliases.

**Comment by AlexWaygood** [comment]
I think we can tick off mypy now, with the release of 0.920?

**Comment by JelleZijlstra** [comment]
We should be done now :)

**Comment by srittau** [comment]
We should replace remaining uses of `Union` and `Optional`.

**Comment by AlexWaygood** [comment]
I'm reopening this to track the remaining mypy bugs

**Comment by Avasam** [comment]
> I'm reopening this to track the remaining mypy bugs.

What is/are the bug(s) left? Is it listed on mypy side?

**Comment by AlexWaygood** [comment]
> > I'm reopening this to track the remaining mypy bugs.
> 
> What is/are the bug(s) left? Is it listed on mypy side?

None left now (to my knowledge)! All the significant bugs are now fixed on mypy `master` -- we're just waiting on a new release of mypy that includes the fixes. Then we can close this out!
