### ISSUE TITLE
PEP 613 (Explicit Type Aliases) tracker

### ISSUE THREAD

**Issue by srittau** [python/typeshed#4913]
This issue is supposed to track when we can start to use explicit type aliases ([PEP 613](https://www.python.org/dev/peps/pep-0613/)) in typeshed. Support is needed in released versions of:

* [x] mypy (python/mypy#9404)
    + [x] python/mypy#12422
* [x] pytype (google/pytype#787)
    + [x] google/pytype#1159
* [x] pyright (microsoft/pyright#655)
* [x] pyre
* [x] PyCharm [PY-42334](https://youtrack.jetbrains.com/issue/PY-42334)

**Comment by srittau** [comment]
@rchen152 I am sorry for the mention spam, but does pytype support PEP 613? If not, would you mind me creating a ticket that we can reference from here?

**Comment by sproshev** [comment]
Supported since PyCharm 2020.3 https://youtrack.jetbrains.com/issue/PY-42334

**Comment by rchen152** [comment]
pytype doesn't support this yet. Opened https://github.com/google/pytype/issues/787.

**Comment by srittau** [comment]
I used this simple script to test this feature.

```python
from typing_extensions import TypeAlias

Alias1 = str
Alias2: TypeAlias = str

def foo() -> Alias1: pass
def bar() -> Alias2: pass

reveal_type(foo)
reveal_type(bar)
```

**Comment by srittau** [comment]
mypy 0.930 now supports this.

**Comment by rchen152** [comment]
pytype-2022.03.21 supports explicit type aliases.

**Comment by AlexWaygood** [comment]
Seems like there's nothing left to do here :)

**Comment by srittau** [comment]
Reopening as mypy still seems to have problems. #7534

**Comment by AlexWaygood** [comment]
@rchen152, #7534 also has several pytype errors, but they all look like valid type aliases to me — any idea what the problem is? :)

**Comment by rchen152** [comment]
Whoops, that's embarrassing XD
It looks almost like the type aliases aren't being stored at all - I'll investigate.

**Comment by srittau** [comment]
mypy and pytype are now fixed. 🎉

**Comment by laundmo** [comment]
Does the closing of this issue mean that TypeAlias can now be used in TypeShed?

if yes, this should probably be edited:
https://github.com/python/typeshed/blob/be64b01e6cee5cbcb98e8934abacf00f01acbeb5/CONTRIBUTING.md?plain=1#L241-L242

**Comment by AlexWaygood** [comment]
> Does the closing of this issue mean that TypeAlias can now be used in TypeShed?
> 
> if yes, this should probably be edited:
> 
> https://github.com/python/typeshed/blob/be64b01e6cee5cbcb98e8934abacf00f01acbeb5/CONTRIBUTING.md?plain=1#L241-L242

It does — and yes, `CONTRIBUTING` does need to be edited :) I think the guidance on `ParamSpec` is also slightly out of date.

PR welcome, if you'd like to help out!

**Comment by kkirsche** [comment]
> > Does the closing of this issue mean that TypeAlias can now be used in TypeShed?
> > if yes, this should probably be edited:
> > https://github.com/python/typeshed/blob/be64b01e6cee5cbcb98e8934abacf00f01acbeb5/CONTRIBUTING.md?plain=1#L241-L242
> 
> It does — and yes, `CONTRIBUTING` does need to be edited :) I think the guidance on `ParamSpec` is also slightly out of date.
> 
> PR welcome, if you'd like to help out!

#8397 created to address this
