### ISSUE TITLE
VERSIONS sub-module tracker

### ISSUE THREAD

**Issue by srittau** [python/typeshed#5469]
`VERSIONS` supports sub-modules now. This has no impact on mypy, pytype, and pyright that already support the `VERSIONS` file. They just ignore sub-module entries. Once they recognize them, we can remove the `version_info` guards from the affected sub-modules.

* [x] mypy (python/mypy#10483)
* [x] pytype (google/pytype#923)
* [x] pyright (microsoft/pyright#1868)
