### ISSUE TITLE
PEP 673 (Self Type) tracker

### ISSUE THREAD

**Issue by srittau** [python/typeshed#6300]
This issue is supposed to track when we can start to use `typing_extensions.Self` ([PEP 673](https://www.python.org/dev/peps/pep-0673/)) in typeshed. Support is needed in released versions of:

* [x] PEP accepted
* [x] mypy (python/mypy#14041)
* [ ] pytype
* [x] pyright (microsoft/pyright#2515)
* [ ] pyre
* [x] PyCharm (nice to have, but not required)

**Comment by Gobot1234** [comment]
I've opened a PR for this to mypy https://github.com/python/mypy/pull/11666 (although it's marked as a draft).

**Comment by thomkeh** [comment]
PEP has been accepted: https://mail.python.org/archives/list/typing-sig@python.org/thread/J7BWL5KWOPQQK5KFWKENVLXW6UGSPTGI/

**Comment by johnthagen** [comment]
PyCharm 2022.3 supports the `Self` type

- https://www.jetbrains.com/pycharm/whatsnew/#editor

**Comment by cj81499** [comment]
The `mypy` PR in the issue description appears to be merged. Is there something still blocked use from a `mypy` perspective? Or does the description need to be updated?

**Comment by TeamSpen210** [comment]
It's merged, but still awaiting a release.

**Comment by srittau** [comment]
Once that happens, we can try start using it in typeshed. I suspect that pytype will accept it as it's quite permissive. I don't know about pyre.

**Comment by thomkeh** [comment]
I can find 10 hits for `from typing_extensions import Self` in the pyre integration tests:

https://github.com/facebook/pyre-check/blob/2da1844a4ae1861bf5b765a80feaf463a62d8831/source/analysis/test/integration/typeVariableTest.ml#L3593

So I'd guess that pyre support is pretty good.

**Comment by johnthagen** [comment]
mypy 1.0 has released with support for `Self`:

- https://pypi.org/project/mypy/1.0.0/
- https://mypy-lang.blogspot.com/2023/02/mypy-10-released.html

**Comment by srittau** [comment]
We started using this in the stdlib, and nothing exploded. I guess this means this is supported now.
