### ISSUE TITLE
PEP 655 (Required TypedDict items) tracker

### ISSUE THREAD

**Issue by srittau** [python/typeshed#6301]
This issue is supposed to track when we can start to use `Required`/`NotRequired` ([PEP 655](https://www.python.org/dev/peps/pep-0655/)) in typeshed. Support is needed in released versions of:

* [x] PEP accepted
* [X] mypy (python/mypy#10370)
* [ ] pytype
* [x] pyright (microsoft/pyright#1554)
* [x] pyre
* [x] PyCharm ([PY-53611](https://youtrack.jetbrains.com/issue/PY-53611/Support-PEP-655-typingRequiredtypingNotRequired-for-TypedDicts))

**Comment by JelleZijlstra** [comment]
I feel like we should also wait for the PEP to be accepted. typing-extensions can include experimental features that may be rejected, but I feel like typeshed should not.

**Comment by srittau** [comment]
This is now fully supported in mypy.

**Comment by JelleZijlstra** [comment]
I think it supports only one of Required and NotRequired? That's what the initial PR said but I haven't verified with the release.

**Comment by srittau** [comment]
Quick tests confirms that it works with both:

```python
from typing_extensions import TypedDict, Required, NotRequired

class NonTotal(TypedDict, total=False):
    foo: int
    bar: Required[str]
    
nt1: NonTotal = {"foo": 123, "bar": ""}
nt2: NonTotal = {"foo": "", "bar": 123}  # incompatible types
nt3: NonTotal = {"foo": 123}  # missing key "bar"
nt4: NonTotal = {"bar": ""}

class Total(TypedDict, total=True):
    foo: int
    bar: NotRequired[str]
    
t1: Total = {"foo": 123, "bar": ""}
t2: Total = {"foo": "", "bar": 123}  # incompatible types
t3: Total = {"bar": ""}  # missing key "foo"
t4: Total = {"foo": 123}  
```

**Comment by gregoiredx** [comment]
Hello @srittau, just to let you know you can check the "PEP accepted" checkbox, see https://groups.google.com/g/dev-python/c/odKM_OpDES0 and https://peps.python.org/pep-0655/

**Comment by srittau** [comment]
I've used `NotRequired` in #8089 and our tests passed. So it seems that pytype at least accepts `NotRequired`, even if it doesn't fully support it, which would be enough for me. Cc @rchen152 for feedback.

Also cc @pradeep90 and @shannonzhu: Does pyre support `Required`/`NotRequired` for `TypedDict`?

**Comment by pradeep90** [comment]
> I've used `NotRequired` in #8089 and our tests passed. So it seems that pytype at least accepts `NotRequired`, even if it doesn't fully support it, which would be enough for me. Cc @rchen152 for feedback.
> 
> Also cc @pradeep90 and @shannonzhu: Does pyre support `Required`/`NotRequired` for `TypedDict`?

@srittau  No, we don't yet support `Required`/`NotRequired`. I'll implement it by the end of the month.

**Comment by lancelote** [comment]
Available in PyCharm >= 2022.2 EAP 4 https://youtrack.jetbrains.com/issue/PY-53611/Support-PEP-655-typingRequiredtypingNotRequired-for-TypedDicts

**Comment by pradeep90** [comment]
> @srittau No, we don't yet support `Required`/`NotRequired`. I'll implement it by the end of the month.

Added support in Pyre v0.9.15.

**Comment by srittau** [comment]
Since the pytype checks run against the zxcvbn stubs, which already use `NotRequired` successfully and all other type checkers support it, I'm closing this. 🎉
