### ISSUE TITLE
PEP 646 (Variadic Generics) tracker

### ISSUE THREAD

**Issue by srittau** [python/typeshed#8708]
* [x] mypy (https://github.com/python/mypy/issues/12280)
* [ ] pytype (https://github.com/google/pytype/issues/1525)
* [x] pyright
* [x] pyre
* [ ] PyCharm (nice to have, but not required)

**Comment by AlexWaygood** [comment]
I've ticked off pyright; I believe it's supported PEP 646 for a while now.

**Comment by AlexWaygood** [comment]
PEP 646 lists Pyre as [providing a reference implementation of the PEP](https://peps.python.org/pep-0646/#reference-implementation), so they probably also have pretty good support.

**Comment by AlexWaygood** [comment]
PEP 646 support would be useful for (feel free to edit this):

- `asyncio.events.Handle`
- `asyncio.events.TimerHandle`
- `asyncio.events.AbstractEventLoop.call_at`
- `asyncio.events.AbstractEventLoop.call_later`
- `asyncio.events.AbstractEventLoop.call_soon`
- `asyncio.base_events.BaseEventLoop.call_at`
- `asyncio.base_events.BaseEventLoop.call_later`
- `asyncio.base_events.BaseEventLoop.call_soon`
- (Maybe): `functools.partial` (#8703)
- Various functions in the `keyboard` third-party stubs:
  - https://github.com/python/typeshed/blob/8a8db9c6d4e39b4c530b6b6ce03bb6869c394419/stubs/keyboard/keyboard/mouse.pyi#L47-L56
  - https://github.com/python/typeshed/blob/8a8db9c6d4e39b4c530b6b6ce03bb6869c394419/stubs/keyboard/keyboard/__init__.pyi#L37
  - https://github.com/python/typeshed/blob/8a8db9c6d4e39b4c530b6b6ce03bb6869c394419/stubs/keyboard/keyboard/__init__.pyi#L58-L65

Note that we won't be able to use PEP 646 as it currently stands for `builtins.map`, `builtins.zip` or `asyncio.gather`: https://github.com/python/cpython/pull/32103#discussion_r836917997

**Comment by srittau** [comment]
This is now used in several places.
